pipeline {
    agent any

    environment {
        MY_VARIABLE = 'var'
    }
    options {
        skipDefaultCheckout() // Ignorar o checkout padrão
    }
     parameters {
        string(name: 'param', defaultValue: 'default_value', description: 'Parâmetro')
    }
    triggers {
        cron('H */4 * * 1-5') // Executar a cada 4 horas de segunda a sexta-feira
    }
    
    stages {
        stage('Clonar Repositório') {
            steps {
                git 'https://github.com/krolcm/Trabalho-DEVOPS-PUC.git'
            }
        }
        
        stage('Instalar Dependências') {
            steps {
                bat 'npm install'
            }
        }
        
        stage('Executar Testes') {
            steps {
                // Executar os testes Cypress em primeiro plano
                bat './node_modules/.bin/cypress run --reporter-options configFile=package.json'
            }
        }
        stage('Input Stage') {
            steps {
                input(message: 'Por favor, confirme se deseja continuar para a etapa paralela')
            }
        }
        stage('Parallel Stages') {
            parallel {
                stage('Parallel Stage 1') {
                    steps {
                        // Passos para a etapa paralela 1
                        echo 'Executando etapa paralela 1'
                    }
                }
                stage('Parallel Stage 2') {
                    steps {
                        // Passos para a etapa paralela 2
                        echo 'Executando etapa paralela 2'
                    }
                }
            }
        }
    
    post {
      success {
            echo 'pipeline bem-sucedido.'
        }
        
        failure {
            echo 'pipeline falhou.'
        }
    }
}
