name: Geração de Release Notes

on:
  push:
    branches:
      - main

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Gerar Release Notes
        run: npm run release
        
      - name: Tornar standard-version executável
        run: chmod +x node_modules/.bin/standard-version

      - name: Commit e push das Release Notes
        run: |
          git config --local user.email "krolcm22@gmail.com"
          git config --local user.name "krolcm"
          git add CHANGELOG.md
          git commit -m "chore(release): Generate Release Notes"
          git push origin main
