name: Geração de Release Notes

on:
  push:
    branches:
      - main

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Tornar standard-version executável
        run: chmod +x node_modules/.bin/standard-version
        
      - name: Configurar o Git identity
        run: |
          git config --local user.email "krolcm22@gmail.com"
          git config --local user.name "krolcm"
          
      - name: Gerar Release Notes
        run: npm run release 

      - name: Verificar alterações
        id: check_changes
        run: |
          git diff --exit-code || echo "Changes detected"
          git diff --cached --exit-code || echo "Staged changes detected"

      - name: Commit e push das Release Notes
        if: steps.check_changes.outputs.check_changes == 'Changes detected' || steps.check_changes.outputs.check_changes == 'Staged changes detected'
        run: |
          git add CHANGELOG.md
          git commit -m "chore(release): Generate Release Notes"
          git push origin main
